# Generated by Django 5.0 on 2023-12-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qno', models.CharField(max_length=2)),
                ('question', models.TextField()),
                ('ans', models.TextField(blank=True, null=True)),
                ('correct', models.BooleanField()),
            ],
        ),
    ]
