# Generated by Django 5.0 on 2023-12-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_remove_questions_correct_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
