# Generated by Django 5.0 on 2023-12-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_alter_answer_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='correct',
            field=models.CharField(choices=[('Correct', 'Correct'), ('Wrong', 'Wrong'), ('-', '-')], default='-', max_length=8),
        ),
    ]
