# Generated by Django 5.0.6 on 2024-05-18 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_answer_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='ans',
            new_name='answer',
        ),
    ]
