# Generated by Django 5.0 on 2023-12-25 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='answer',
        ),
    ]
