# Generated by Django 5.0 on 2023-12-26 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='role',
        ),
    ]
