# Generated by Django 5.0.6 on 2024-05-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_delete_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalPoints',
            fields=[
                ('username', models.CharField(max_length=100)),
                ('points', models.IntegerField(default=0)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
