# Generated by Django 5.0.6 on 2024-05-18 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TotalPoints',
        ),
    ]
